#!/usr/bin/env python3
"""
Hook Installer — installs SECA pre-commit hook into .git/hooks/

Usage: python install_hooks.py [--project-root DIR]
Default project root: two levels up from this script.

What it does:
  1. Checks .git/ exists
  2. Backs up existing pre-commit hook (if any)
  3. Writes a shim that calls _ai_evolution/scripts/pre_commit_check.py
  4. Windows-compatible (uses .py shim, not bash)
"""

import os
import shutil
import stat
import sys
from pathlib import Path


def get_project_root() -> Path:
    """Resolve project root: --project-root flag or two levels up."""
    if "--project-root" in sys.argv:
        idx = sys.argv.index("--project-root")
        if idx + 1 < len(sys.argv):
            return Path(sys.argv[idx + 1])
    return Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))).parent


# The hook shim script (cross-platform Python)
HOOK_CONTENT = '''#!/usr/bin/env python3
"""
Git pre-commit hook — generated by SECA install_hooks.py
Calls _ai_evolution/scripts/pre_commit_check.py
Bypass: git commit --no-verify
"""
import os
import subprocess
import sys

# Resolve project root from .git/hooks/
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
check_script = os.path.join(project_root, "_ai_evolution", "scripts", "pre_commit_check.py")

if not os.path.exists(check_script):
    print(f"WARNING: {check_script} not found — skipping pre-commit checks")
    sys.exit(0)

result = subprocess.run(
    [sys.executable, check_script, "--project-root", project_root],
    timeout=15
)
sys.exit(result.returncode)
'''


def main():
    project_root = get_project_root()
    git_dir = project_root / ".git"

    # 1. Check .git/ exists
    if not git_dir.is_dir():
        print(f"ERROR: {git_dir} not found.")
        print("Initialize Git first: git init")
        print("Then re-run this script.")
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_file = hooks_dir / "pre-commit"

    # 2. Backup existing hook
    if hook_file.exists():
        backup = hooks_dir / "pre-commit.backup"
        shutil.copy2(hook_file, backup)
        print(f"Backed up existing hook to: {backup}")

    # 3. Write shim
    with open(hook_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(HOOK_CONTENT)

    # 4. Make executable (Unix/macOS)
    try:
        hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)
    except OSError:
        pass  # Windows doesn't need this

    print(f"Pre-commit hook installed: {hook_file}")
    print("Bypass: git commit --no-verify")
    print("Uninstall: delete .git/hooks/pre-commit")


if __name__ == "__main__":
    main()
